# Module: NumPy Assignments
## Lesson: NumPy



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

# SOLUTIONS:

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
import numpy as np

In [ ]:
# 1)

# original array creation
arr101 = np.random.randint(1, 21, size= (5,5))
print("1)\n\nOriginal Array:\n",arr101)

# replacement of original array creation
arr101[:,2] = 1
print("\nModified Array:\n", arr101)

# 2)

# original array creation
arr102 = np.random.randint(1,17, size= (4,4))
print("\n2)\n\nOriginal Array:\n",arr102)

# diagonal replacement
# arr102[np.arange(4), np.arange(4)] = 0
np.fill_diagonal(arr102,0)
print("\nModified Array:\n", arr102)

1)

Original Array:
 [[ 8  7 14  1  4]
 [17  4  4 17  2]
 [10 16 15 18 10]
 [18  2  6  8 13]
 [ 3 12  1  7 17]]

Modified Array:
 [[ 8  7  1  1  4]
 [17  4  1 17  2]
 [10 16  1 18 10]
 [18  2  1  8 13]
 [ 3 12  1  7 17]]

2)

Original Array:
 [[ 2 13  2  9]
 [11  3 10  9]
 [ 8  7  8  9]
 [12 10  5 15]]

Modified Array:
 [[ 0 13  2  9]
 [11  0 10  9]
 [ 8  7  0  9]
 [12 10  5  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [109]:
# 1)

# original array creation
arr201 = np.random.randint(1,37, size = (6,6))
print("1)\n\n Original array creation:\n", arr201)

# Sub-array
print("\nSub-array:\n", arr201[2:5,1:4])

#2)
# original array creation
arr202 = np.random.randint(50,size = (5,5))
print("\n2)\n\n Original array creation:\n", arr202)

# Elements on the border
print("\nElements on the border:\n",
      np.concatenate(
          (arr202[0,:],
           arr202[1:-1,-1],
           arr202[1:-1,0],
           arr202[-1,:])))


1)

 Original array creation:
 [[ 2  9 15 21  6 31]
 [14 34 14 25  3 21]
 [25 34 36 23  4 29]
 [21 15 36 27 35 18]
 [25  5 36 36 26 33]
 [33 25  4 22  9  4]]

Sub-array:
 [[34 36 23]
 [15 36 27]
 [ 5 36 36]]

2)

 Original array creation:
 [[39 43 32 31 40]
 [33 32 48 12 34]
 [24 41 13 40 49]
 [ 1  6 18 44 16]
 [ 5 44  3  4 14]]

Elements on the border:
 [39 43 32 31 40 34 49 16 33 24  1  5 44  3  4 14]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
#1)

# array 01:
arr301 = np.random.randint(1, 50,size = (3,4))
print("1)\n\n Array 01:\n", arr301)

# array 02:
arr302 = np.random.randint(1, 50,size = (3,4))
print("\n Array 02:\n", arr302)

#Element wise addition
arr303 = arr301 + arr302
print("\n Element wise addition:\n", arr303)

#Element wise subtraction
arr304 = arr301 - arr302
print("\n Element wise subtraction:\n", arr304)

#Element wise multiplication
arr305 = arr301 * arr302
print("\n Element wise multiplication:\n", arr305)

#Element wise Division
arr306 = arr301 / arr302
print("\n Element wise division:\n", arr306)


1)

 Array 01:
 [[ 1  1 36 17]
 [35  1 12 31]
 [11 45  9 36]]

 Array 02:
 [[16 27 46 27]
 [31 20 32 13]
 [32 43 18 25]]

 Element wise addition:
 [[17 28 82 44]
 [66 21 44 44]
 [43 88 27 61]]

 Element wise subtraction:
 [[-15 -26 -10 -10]
 [  4 -19 -20  18]
 [-21   2  -9  11]]

 Element wise multiplication:
 [[  16   27 1656  459]
 [1085   20  384  403]
 [ 352 1935  162  900]]

 Element wise division:
 [[0.0625     0.03703704 0.7826087  0.62962963]
 [1.12903226 0.05       0.375      2.38461538]
 [0.34375    1.04651163 0.5        1.44      ]]


In [107]:
#2

#Array Creation:

arr307 = np.random.randint(1, 17, size = (4,4))
print("\n2)\n\n Array 03:\n", arr307)

#Row-wise sum
print("\n Row-wise sum of Array:\n", np.sum(arr307, axis = 1))

#Column-wise sum
print("\n Column-wise sum of Array:\n", np.sum(arr307, axis = 0))



2)

 Array 03:
 [[ 6  7 12  3]
 [11 15  1 14]
 [ 6  9 11  2]
 [16  9 10  2]]

 Row-wise sum of Array:
 [28 41 28 37]

 Column-wise sum of Array:
 [39 40 34 21]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [121]:
# 1)

# original array creation
arr401 = np.random.randint(-5,20, size = (5,5))
print("1)\n\n Original array creation:\n", arr401)

print("\nMean :\t\t\t",arr401.mean())
print("Median :\t\t",np.median(arr401))
print("Standard Deviation :\t",arr401.std())
print("Variance :\t\t",arr401.var())

1)

 Original array creation:
 [[ 5 12  4 13 11]
 [13 17  8  4 16]
 [-4 -1  5  8 -3]
 [ 7  5  0 12  0]
 [-3 -4  8 -4  6]]

Mean :			 5.4
Median :		 5.0
Standard Deviation :	 6.368673331236264
Variance :		 40.56


In [134]:
# 2)

# original array creation
arr402 = np.arange(1,10,1).reshape(3,3)

# arr402 = np.random.randint(1,10, size = (3,3))
print("2)\n\n Original array creation:\n", arr402)

#Normalised Array = (Array - Mean) / Standard Deviation
arr403 = (arr402 - np.mean(arr402)) / np.std(arr402)

print("\nNormalised Array :\n",arr403)

2)

 Original array creation:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalised Array :
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [138]:
# 1)

# array 01:
arr501 = np.random.randint(1, 11, size = (3,3))
print("1)\n\n Array 01:\n", arr501)

# array 02:
arr502 = np.random.randint(1, 11,size = (3,))
print("\n Array 02:\n", arr502)

# # Add the 1D array to each row of the 2D array using broadcasting
print("\nAdd the 1D array to each row of the 2D array using broadcasting:\n",arr501 + arr502)

1)

 Array 01:
 [[3 2 8]
 [5 1 9]
 [8 7 3]]

 Array 02:
 [10  9  5]

Add the 1D array to each row of the 2D array using broadcasting:
 [[13 11 13]
 [15 10 14]
 [18 16  8]]


In [139]:
# 2)

# array 01:
arr503 = np.random.randint(1, 11, size = (3,3))
print("2)\n\n Array 01:\n", arr503)

# array 02:
arr504 = np.random.randint(1, 11,size = (3,))
print("\n Array 02:\n", arr504)

# # Subtract the 1D array to each row of the 2D array using broadcasting
print("\nSubtract the 1D array to each row of the 2D array using broadcasting:\n",arr503 - arr504)

2)

 Array 01:
 [[ 4  5  6]
 [10  2  9]
 [ 7 10  8]]

 Array 02:
 [4 8 7]

Subtract the 1D array to each row of the 2D array using broadcasting:
 [[ 0 -3 -1]
 [ 6 -6  2]
 [ 3  2  1]]
