# Module: NumPy Assignments
## Lesson: NumPy


# SOLUTIONS:

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
import numpy as np

In [3]:
# 1)

# original array creation
arr101 = np.random.randint(1, 21, size= (5,5))
print("1)\n\nOriginal Array:\n",arr101)

# replacement of original array creation
arr101[:,2] = 1
print("\nModified Array:\n", arr101)

# 2)

# original array creation
arr102 = np.random.randint(1,17, size= (4,4))
print("\n2)\n\nOriginal Array:\n",arr102)

# diagonal replacement
# arr102[np.arange(4), np.arange(4)] = 0
np.fill_diagonal(arr102,0)
print("\nModified Array:\n", arr102)

1)

Original Array:
 [[ 1  1  5 18 18]
 [15  2 19  6  9]
 [11  2  7  8 19]
 [18 15  3  9 16]
 [ 8 19 17 12  6]]

Modified Array:
 [[ 1  1  1 18 18]
 [15  2  1  6  9]
 [11  2  1  8 19]
 [18 15  1  9 16]
 [ 8 19  1 12  6]]

2)

Original Array:
 [[16 12 14 15]
 [ 8 12 14 14]
 [ 6  9 15  9]
 [16 10 10  5]]

Modified Array:
 [[ 0 12 14 15]
 [ 8  0 14 14]
 [ 6  9  0  9]
 [16 10 10  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
# 1)

# original array creation
arr201 = np.random.randint(1,37, size = (6,6))
print("1)\n\n Original array creation:\n", arr201)

# Sub-array
print("\nSub-array:\n", arr201[2:5,1:4])

#2)
# original array creation
arr202 = np.random.randint(50,size = (5,5))
print("\n2)\n\n Original array creation:\n", arr202)

# Elements on the border
print("\nElements on the border:\n",
      np.concatenate(
          (arr202[0,:],
           arr202[1:-1,-1],
           arr202[1:-1,0],
           arr202[-1,:])))


1)

 Original array creation:
 [[27 35 25 13 23  5]
 [32 24 21 33 22 11]
 [ 6 19 19 23  5 23]
 [18 23 34 15 21  1]
 [ 8  8 14  9 20 24]
 [18 24 33 21 11  5]]

Sub-array:
 [[19 19 23]
 [23 34 15]
 [ 8 14  9]]

2)

 Original array creation:
 [[21 37 22 15 10]
 [ 9 39  9 48 21]
 [40 23  1 37 40]
 [ 6 30 24 32  8]
 [ 0 29 49 21 39]]

Elements on the border:
 [21 37 22 15 10 21 40  8  9 40  6  0 29 49 21 39]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [5]:
#1)

# array 01:
arr301 = np.random.randint(1, 50,size = (3,4))
print("1)\n\n Array 01:\n", arr301)

# array 02:
arr302 = np.random.randint(1, 50,size = (3,4))
print("\n Array 02:\n", arr302)

#Element wise addition
arr303 = arr301 + arr302
print("\n Element wise addition:\n", arr303)

#Element wise subtraction
arr304 = arr301 - arr302
print("\n Element wise subtraction:\n", arr304)

#Element wise multiplication
arr305 = arr301 * arr302
print("\n Element wise multiplication:\n", arr305)

#Element wise Division
arr306 = arr301 / arr302
print("\n Element wise division:\n", arr306)


1)

 Array 01:
 [[36 24 24 39]
 [10 32 21 28]
 [ 8 27 37 29]]

 Array 02:
 [[21 22 13 18]
 [24 30 38 45]
 [ 5 22  5 41]]

 Element wise addition:
 [[57 46 37 57]
 [34 62 59 73]
 [13 49 42 70]]

 Element wise subtraction:
 [[ 15   2  11  21]
 [-14   2 -17 -17]
 [  3   5  32 -12]]

 Element wise multiplication:
 [[ 756  528  312  702]
 [ 240  960  798 1260]
 [  40  594  185 1189]]

 Element wise division:
 [[1.71428571 1.09090909 1.84615385 2.16666667]
 [0.41666667 1.06666667 0.55263158 0.62222222]
 [1.6        1.22727273 7.4        0.70731707]]


In [6]:
#2

#Array Creation:

arr307 = np.random.randint(1, 17, size = (4,4))
print("\n2)\n\n Array 03:\n", arr307)

#Row-wise sum
print("\n Row-wise sum of Array:\n", np.sum(arr307, axis = 1))

#Column-wise sum
print("\n Column-wise sum of Array:\n", np.sum(arr307, axis = 0))



2)

 Array 03:
 [[ 8  6  7  7]
 [ 9  1  1  6]
 [13 12 16  3]
 [11  7 15 13]]

 Row-wise sum of Array:
 [28 17 44 46]

 Column-wise sum of Array:
 [41 26 39 29]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [7]:
# 1)

# original array creation
arr401 = np.random.randint(-5,20, size = (5,5))
print("1)\n\n Original array creation:\n", arr401)

print("\nMean :\t\t\t",arr401.mean())
print("Median :\t\t",np.median(arr401))
print("Standard Deviation :\t",arr401.std())
print("Variance :\t\t",arr401.var())

1)

 Original array creation:
 [[-5  8 17  6  1]
 [ 3 -2  7 -1 -5]
 [ 8 16 14 -1 -3]
 [-2 16 15 12  7]
 [10 18  1 12  9]]

Mean :			 6.44
Median :		 7.0
Standard Deviation :	 7.266801221995824
Variance :		 52.8064


In [8]:
# 2)

# original array creation
arr402 = np.arange(1,10,1).reshape(3,3)

# arr402 = np.random.randint(1,10, size = (3,3))
print("2)\n\n Original array creation:\n", arr402)

#Normalised Array = (Array - Mean) / Standard Deviation
arr403 = (arr402 - np.mean(arr402)) / np.std(arr402)

print("\nNormalised Array :\n",arr403)

2)

 Original array creation:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalised Array :
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [9]:
# 1)

# array 01:
arr501 = np.random.randint(1, 11, size = (3,3))
print("1)\n\n Array 01:\n", arr501)

# array 02:
arr502 = np.random.randint(1, 11,size = (3,))
print("\n Array 02:\n", arr502)

# # Add the 1D array to each row of the 2D array using broadcasting
print("\nAdd the 1D array to each row of the 2D array using broadcasting:\n",arr501 + arr502)

1)

 Array 01:
 [[10  5  6]
 [ 6 10  6]
 [ 3  5  4]]

 Array 02:
 [2 5 5]

Add the 1D array to each row of the 2D array using broadcasting:
 [[12 10 11]
 [ 8 15 11]
 [ 5 10  9]]


In [10]:
# 2)

# array 01:
arr503 = np.random.randint(1, 11, size = (3,3))
print("2)\n\n Array 01:\n", arr503)

# array 02:
arr504 = np.random.randint(1, 11,size = (3,))
print("\n Array 02:\n", arr504)

# # Subtract the 1D array to each row of the 2D array using broadcasting
print("\nSubtract the 1D array to each row of the 2D array using broadcasting:\n",arr503 - arr504)

2)

 Array 01:
 [[ 1  5  3]
 [10  5  5]
 [ 6  4  2]]

 Array 02:
 [6 1 5]

Subtract the 1D array to each row of the 2D array using broadcasting:
 [[-5  4 -2]
 [ 4  4  0]
 [ 0  3 -3]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [17]:
# 1)

# original array creation
arr601 = np.random.randint(1,19, size = (3,3))
print("1)\n\n Original array creation:\n", arr601)

# Determinant
print("\nDeterminant of Array :\t",np.linalg.det(arr601))

# Inverse
print("\nInverse of Array :\n",np.linalg.inv(arr601))

# Eigenvalues and eigenvectors
print("\nEigen Values of Array :\n",np.linalg.eigvals(arr601))

1)

 Original array creation:
 [[13  7  3]
 [ 4 11  9]
 [ 1  3 15]]

Determinant of Array :	 1440.0000000000005

Inverse of Array :
 [[ 0.09583333 -0.06666667  0.02083333]
 [-0.03541667  0.13333333 -0.07291667]
 [ 0.00069444 -0.02222222  0.07986111]]

Eigen Values of Array :
 [21.24284824 12.20146463  5.55568713]


In [22]:
# 2)

# Array creation:
# array 01:
arr602 = np.random.randint(1, 10, size = (2,3))
print("2)\n\n Array 01:\n", arr602)

# array 02:
arr603 = np.random.randint(1, 10,size = (3,2))
print("\n Array 02:\n", arr603)

# Matrix dot product operation:
print("\nMatrix dot product of Array 1 and Array 2:\n", np.dot(arr602, arr603))

2)

 Array 01:
 [[2 3 6]
 [4 7 9]]

 Array 02:
 [[8 9]
 [3 2]
 [9 9]]

Matrix dot product of Array 1 and Array 2:
 [[ 79  78]
 [134 131]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [32]:
# 1)

# original array creation
arr701 = np.arange(1, 10).reshape(3,3)
print("1)\n\n Original array creation:\n", arr701)

# Reshape the array to shape (1, 9)
arr702 = arr701.reshape(1, 9)
print("\n Reshaped array (1x9):\n", arr702)

# Reshape the array to shape (9, 1)
arr703 = arr702.reshape(9, 1)
print("\n Reshaped array (9x1):\n", arr703)


1)

 Original array creation:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Reshaped array (1x9):
 [[1 2 3 4 5 6 7 8 9]]

 Reshaped array (9x1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [37]:
# 2)

# original array creation
arr704 = np.random.randint(101, 201, size = (5,5))
print("2)\n\n Original array creation:\n", arr704)

# Flatten the array
arr705 = arr704.flatten()
print("\n Flattened array:\n", arr705)

#  Reshape the array to shape (5,5)
arr706 = arr705.reshape(5, 5)
print("\n Reshaped array (5x5):\n", arr706)

2)

 Original array creation:
 [[177 148 137 106 167]
 [179 119 158 172 134]
 [181 105 101 191 160]
 [130 138 114 194 172]
 [176 197 126 118 186]]

 Flattened array:
 [177 148 137 106 167 179 119 158 172 134 181 105 101 191 160 130 138 114
 194 172 176 197 126 118 186]

 Reshaped array (5x5):
 [[177 148 137 106 167]
 [179 119 158 172 134]
 [181 105 101 191 160]
 [130 138 114 194 172]
 [176 197 126 118 186]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [41]:
# 1)

# original array creation:

# original array creation
arr801 = np.random.randint(1,51, size = (5,5))
print("1)\n\n Original array creation:\n", arr801)

# Element at the corners of the array
print("\nElements at the corner of the Array :\t",arr801[[0,0,-1,-1],[0,-1,0,-1]])

1)

 Original array creation:
 [[ 1 12  2 35 38]
 [46 10 40  4  6]
 [29 39 25 39 36]
 [ 3 12  8 12 28]
 [40  3 20 35 39]]

Elements at the corner of the Array :	 [ 1 38 40 39]


In [45]:
# 2)

# original array creation
arr802 = np.random.randint(1,101, size = (4,4))
print("2)\n\n Original array creation:\n", arr802)

# Changing all elements above 50 as 50.
arr802[arr802>50] = 50

print("\nChanging all elements above 50 as 50 :\n",arr802)

2)

 Original array creation:
 [[61 21 63 73]
 [28 39 87 64]
 [40 33 19 74]
 [92 87 89 14]]

Changing all elements above 50 as 50 :
 [[50 21 50 50]
 [28 39 50 50]
 [40 33 19 50]
 [50 50 50 14]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [47]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [58]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [59]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[14 10  7  2]
 [ 4 17 19  5]
 [14 15  5  4]
 [ 2  3 18 18]]
Masked array:
[[-- 10 7 2]
 [4 -- -- 5]
 [-- -- 5 4]
 [2 3 -- --]]
Sum of unmasked elements: 42


In [61]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 1  7  9]
 [14  5  4]
 [ 6  3  8]]
Masked array:
[[-- 7 9]
 [14 -- 4]
 [6 3 --]]
Modified masked array:
[[ 7  7  9]
 [14  7  4]
 [ 6  3  7]]


In [ ]:
all_arr = ['arr101', 'arr102', 'arr201', 'arr202', 'arr301', 'arr302', 'arr303', 'arr304', 'arr305', 'arr306', 'arr307', 'arr401', 'arr402', 'arr403', 'arr501', 'arr502', 'arr503', 'arr504', 'arr601', 'arr602', 'arr603', 'arr701', 'arr702', 'arr703', 'arr704', 'arr705', 'arr706', 'arr801', 'arr802']

for arr in all_arr:
    print(arr,":\n",eval(arr),"\n")


In [ ]:
arr901 = np.random.randint(1,101, size = (5,5))
print("Random 5 x 5 array with numbers between 1 and 101:\n",arr901)
# ma.MaskedArray(arr901,mask = np.eye(4, dtype= bool))
arr902 = ma.masked_outside(arr901, 90,10)
print("masked outside 90 and 10:\n",arr902)

arr903 = ma.mask_rowcols(arr902,axis = 0)
print("mask row if any one mask present:\n",arr903)

arr904 = ma.mask_rowcols(arr902,axis = 1)
print("mask column if any one mask present:\n",arr904)

arr905 = ma.masked_where(arr901<40, arr901)
print("masked where < 40:\n",arr905)